FROM alpine:3.20@sha256:77726ef6b57ddf65bb551896826ec38bc3e53f75cdde31354fbffb4f25238ebd as otelc_curl
RUN apk --update add curl

FROM otel/opentelemetry-collector:latest@sha256:6a76e13f1f4a22a6836189b9828e3de64cddae418ff5a15f10715a596ccc08a5

COPY --from=otelc_curl / /

COPY ./otel-collector-config.yaml /etc/otel-collector-config.yaml
USER 0
RUN chmod o+r /etc/otel-collector-config.yaml
USER nobody
