name: Cache (docker)

on:
  workflow_call:
    inputs:
      image_tag:
        type: string
        required: true
      version:
        type: string
        default: v002

concurrency:
  group: cache_docker

jobs:
  cache:
    runs-on: ubuntu-22.04
    steps:

    - name: Check cache
      id: cache-marker-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          /tmp/build-image-cache
        lookup-only: true
        key: ${{ inputs.image_tag }}-${{ inputs.version }}

    - id: docker-stop
      if: ${{ steps.cache-marker-restore.outputs.cache-hit != 'true' }}
      run: |
        sudo systemctl stop docker

    - id: docker-paths
      if: ${{ steps.cache-marker-restore.outputs.cache-hit != 'true' }}
      run: |
        sudo mv /var/lib/docker /var/lib/docker.orig

        sudo mkdir /var/lib/docker

        sudo ls -alh /var/lib/docker.orig
        echo "DO SKIP ME!!!"

    - id: docker-restart
      if: ${{ steps.cache-marker-restore.outputs.cache-hit != 'true' }}
      run: |
        sudo systemctl start docker

    - id: docker-fetch
      if: ${{ steps.cache-marker-restore.outputs.cache-hit != 'true' }}
      run: |
        docker pull ${{ inputs.image_tag }}

    - id: docker-stop-again
      if: ${{ steps.cache-marker-restore.outputs.cache-hit != 'true' }}
      run: |
        sudo systemctl stop docker

    - id: docker-save
      if: ${{ steps.cache-marker-restore.outputs.cache-hit != 'true' }}
      run: |
        echo ZSTD > "/tmp/build-image-cache/marker"

    - name: Save cache marker
      if: ${{ steps.cache-marker-restore.outputs.cache-hit == 'trueXXX' }}
      id: cache-marker-save
      uses: actions/cache/save@v3
      with:
        path: |
          /tmp/build-image-cache
        key: ${{ inputs.image_tag }}-${{ inputs.version }}
