name: Cache (docker)

on:
  workflow_call:
    inputs:
      image_tag:
        type: string
        required: true

concurrency:
  group: cache_docker

jobs:
  cache:
    runs-on: ubuntu-22.04
    steps:

    - id: create tmpfs save directory
      run: |
        echo "CREATE TMPFS"

    - name: Restore cache marker
      id: cache-marker-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          /tmp/cache-marker
        key: ${{ inputs.image_tage }}-marker-v000

    - id: fetch_image
      run: |
        echo ${{ steps.cache-marker-restore.outputs }}
        echo "fetching build image: ${{ inputs.image_tag }} for cache!!!"
