name: Envoy CI

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      rbe:
        type: boolean
        default: true
      managed:
        type: boolean
        default: true
      bazel_extra:
        type: string
        default:


concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.inputs.target }}-ci
  cancel-in-progress: true

jobs:
  repo:
    # if: github.repository == 'envoyproxy/envoy'
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Add safe directory
      run: git config --global --add safe.directory /__w/envoy/envoy

    - id: do_ci
      name: 'Run CI target ${{ inputs.target }}'
      run: |
        echo "run CI target  ${{ inputs.target }} ..."

        echo "run vars ..."

        echo " RBE: ${{ inputs.rbe }}"
        echo " managed: ${{ inputs.rbe }}"
        echo " bazel_extra: ${{ inputs.bazel_extra }}"

        ./ci/run_envoy_docker.sh 'ci/do_ci.sh ${{ inputs.target }}--testing'


      # setup RBE variables, similar to azp/bazel.yml
