name: Envoy CI

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      rbe:
        type: boolean
        default: true
      managed:
        type: boolean
        default: true
      bazel_extra:
        type: string
        default:

      cache_build_image:
        type: string

      command_prefix:
        type: string
        default: ./ci/run_envoy_docker.sh
      command_ci:
        type: string
        default: ./ci/do_ci.sh


concurrency:
  group: ${{ github.head_ref || github.run_id }}-ci-${{ inputs.target }}
  cancel-in-progress: true

jobs:
  do_ci:
    runs-on: ubuntu-22.04
    name: do_ci.sh ${{ inputs.target }}
    steps:
    - uses: actions/checkout@v3
    - name: Add safe directory
      run: git config --global --add safe.directory /__w/envoy/envoy
    - uses: ./.github/actions/cache/restore
      with:
        cache_build_image: ${{ inputs.cache_build_image }}
    - id: do_ci
      name: 'Run CI target ${{ inputs.target }}'
      run: |
        echo "run CI target  ${{ inputs.target }} ..."
        if [[ -n "${{ inputs.command_prefix }}" ]]; then
            ${{ inputs.command_prefix }} '${{ inputs.command_ci }} ${{ inputs.target }}--testing'
        else
            ${{ inputs.command_ci }} ${{ inputs.target }}--testing
        fi
