name: Cache (docker)

on:
  workflow_call:
    inputs:
      image_tag:
        type: string
        required: true
      version:
        type: string
        default: v006

concurrency:
  # not sure about this
  group: cache_docker-${{ inputs.image_tag }}

jobs:
  cache:
    runs-on: ubuntu-22.04
    steps:
    - uses: ./.github/actions/cache/prime
      with:
        cache_build_image: ${{ inputs.cache_build_image }}
