name: Bazel CI

on:
  workflow_call:
    inputs:
      ci:
        required: true
        type: string
      authSSHKey:
        type: string
      buildSetup:
        type: boolean
        default: true
      cacheBazelEnabled:
        type: boolean
        default: true
      cacheBazelKeyFiles:
        type: string
        default: '["./WORKSPACE", "**/*.bzl"]'
        # ' | , !mobile/**, !envoy-docs/**'
      cacheBazelPath:
        type: string
        default: |
          /tmp/envoy-docker-build/.cache/
          /tmp/envoy-docker-build/bazel_root/install/
          /tmp/envoy-docker-build/repository_cache/
          /tmp/envoy-docker-build/bazel_root/base/external
      repoDownstream:
        type: string
      repoDownstreamPath:
        type: string
      runPrefix:
        type: string
        default: ci/run_envoy_docker.sh

permissions:
  contents: read


jobs:
  ci:
    runs-on: ubuntu-20.04
    name: CI (${{ inputs.ci }})
    steps:
    # Repo/s
    - name: 'Checkout repository'
      uses: actions/checkout@v3
      with:
        repository: envoyproxy/envoy
    - name: 'Checkout downstream repository'
      uses: actions/checkout@v3
      if: ${{ inputs.repoDownstream }}
      with:
        repository: "envoyproxy/${{ inputs.repoDownstream }}"
        path: "${{ inputs.repoDownstream }}"
    - run: mv ${{ inputs.downstream }} ${{ inputs.repoDownstreamPath }}
      if: ${{ inputs.repoDownstreamPath }}

    # Auth
    - name: "Set up SSH key (${{ inputs.ci }})"
      uses: shimataro/ssh-key-action@v2.5.1
      if: ${{ inputs.authSSHKey }}
      with:
        key: ${{ inputs.authSSHkey }}
        known_hosts: unnecessary

    # Caching
    - name: Cache bazel workspace
      uses: actions/cache@v3
      if: ${{ inputs.cacheBazelEnabled }}
      with:
        key: "${{ github.base_ref }}-${{ inputs.ci }}-${{ hashFiles('./WORKSPACE', '**/*.bzl') }}"
        path: "${{ inputs.cacheBazelPath }}"
      # fromJson(inputs.cacheBazelKeyFiles)

    - run: df -h
      name: Disk usage at the beginning of the build

    # Target
    - run: "${{ inputs.runPrefix }} ci/do_ci.sh ${{ inputs.ci }}"
      name: "Do ci (${{ inputs.ci }})"
      env:
        NO_BUILD_SETUP: "${{ fromJSON('{\"false\": \"1\", \"true\": \"\"}')[ inputs.buildSetup == true] }}"

        # debugging
        ENVOY_DOCKER_PULL: 1

    - run: |
        df -h
        echo "============================================================"
        du -ch "/tmp/envoy-docker-build" | grep -E "[0-9]{2,}M|[0-9]G"
      name: Disk usage at the end of the build
