name: Envoy/publish

on:
  # This runs untrusted code, do not expose secrets in the verify job
  workflow_dispatch:
    inputs:
      ref:
        description: "Git SHA ref to checkout"
      sha:
        description: "Git SHA of commit HEAD (ie last commit of PR)"
      head_ref:
        description: "Ref for grouping PRs"

  pull_request:

concurrency:
  group: ${{ github.event.inputs.head_ref || github.run_id }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  env:
    uses: ./.github/workflows/env.yml
    secrets: inherit

  ci:
    needs:
    - env
    strategy:
      matrix:
        target:
        - publish
        - publish-other
    uses: ./.github/workflows/_ci.yml
    with:
      target: ${{ matrix.target }}
    secrets: inherit
