name: Envoy/publish

on:
  # This runs untrusted code, do not expose secrets in the verify job
  workflow_dispatch:
    inputs:
      ref:
        description: "Git SHA ref to checkout"
      sha:
        description: "Git SHA of commit HEAD (ie last commit of PR)"
      head_ref:
        description: "Ref for grouping PRs"

  pull_request:

concurrency:
  group: ${{ github.event.inputs.head_ref || github.run_id }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  env:
    uses: ./.github/workflows/env.yml
    secrets: inherit
  cache:
    needs:
    - env
    uses: ./.github/workflows/_docker_cache.yml
    secrets: inherit
    with:
      image_tag: "${{ needs.env.outputs.build_image_ubuntu }}"

  ci:
    needs:
    - env
    - cache
    strategy:
      fail-fast: false
      matrix:
        include:
        - target: publish
          rbe: true
          managed: true
        - target: verify_examples
          rbe: false
          managed: false
          command_prefix: ""
    uses: ./.github/workflows/_ci.yml
    name: CI
    with:
      target: ${{ matrix.target }}
      rbe: ${{ matrix.rbe }}
      managed: ${{ matrix.managed }}
      cache_build_image: ${{ needs.env.outputs.build_image_ubuntu }}
    secrets: inherit
