name: 'TEST AUTH'

on:
  push:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-20.04
    steps:
    - id: appauth
      uses: envoyproxy/toolshed/gh-actions/appauth@550585367f05177a3d4193bf1410e7b6a26142cd
      with:
        key: ${{ secrets.ENVOY_CI_TEST_BOT_KEY }}
        app_id: ${{ secrets.ENVOY_CI_SYNC_TEST_APP_ID }}
    - run: |
        echo "${KEY:0:5}"
      env:
        KEY: ${{ steps.appauth.outputs.token }}
