
on:
  pull_request:

jobs:
  mnt:
    runs-on: ubuntu-24.04
    steps:
    - run: |
        df -h

        DISK_NAME=$(findmnt -n -o SOURCE --target /mnt)


        mount

        sudo ls -alh /mnt

        cat /mnt/DATALOSS_WARNING_README.txt

        free

        sudo swapoff /mnt/swapfile

        sudo umount /mnt

        mount

        echo "$DISK_NAME"
