
on:
  pull_request:

jobs:
  mnt:
    runs-on: ubuntu-24.04
    steps:
    - run: |

        DISK_NAME=$(findmnt -n -o SOURCE --target /mnt)

        df -h
        mount
        sudo ls -alh /mnt
        free
        sudo swapoff /mnt/swapfile
        sudo umount /mnt
        sudo mkfs.ext4 -F "$DISK_NAME"
        sudo mount $DISKNAME /mnt
        sudo mkswap /mnt/swapfile
        sudo swapon /mnt/swapfile
        df -h
        mount
        sudo ls -alh /mnt
        free
